name: deploy to DigitalOcean
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: to-digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir /app
            git clone git@github.com:warnshun/go-clean-blog.git /app/blog
            cd /app/blog
            git fetch
            git reset origin/main --hard
            docker-compose down
            docker-compose up -d
            make migrate-up
            echo 'Deployment successful to Digital Ocean'
